//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPC_Inventory.Seller
{


    public partial class Sales
    {
        protected global::System.Web.UI.WebControls.Repeater TransactionHistoryRepeater;
    }
}
